version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: sa12345!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -S sqlserver -U sa -P sa12345! -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s 

  api:
    container_name: api
    build:
      context: .
      dockerfile: src/CountriesApp.Api/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - sqlserver
    networks:
      - app-network

networks:
  app-network:
    driver: bridge